In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import tab

The goal of this exercise is to learn how to deal with Categorical variables using the `OneHot` Encoder.

```python
X_train = [['Python'], ['Java'], ['Java'], ['C++']]
```


In [2]:
X_train = [['Python'], ['Java'], ['Java'], ['C++']]

1. Using `OneHotEncoder` with `handle_unknown='ignore'`, fit the OneHotEncoder and transform X_train. The expected output is:

   |     | ('C++',) | ('Java',) | ('Python',) |
   | --: | -------: | --------: | ----------: |
   |   0 |        0 |         0 |           1 |
   |   1 |        0 |         1 |           0 |
   |   2 |        0 |         1 |           0 |
   |   3 |        1 |         0 |           0 |

   To get this output, create a DataFrame from the transformed X\*train and the attribute `categories`.

In [18]:
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(X_train)
print(enc.transform(X_train).toarray())
print(enc.categories_)
df = pd.DataFrame(enc.transform(X_train).toarray().astype(np.int8), columns=enc.categories_)
df.head()

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[array(['C++', 'Java', 'Python'], dtype=object)]


,C++,Java,Python
0,0,0,1
1,0,1,0
2,0,1,0
3,1,0,0


2. Transform X_test using the OneHotEncoder fitted on the train set.

```python
X_test = [['Python'], ['Java'], ['C'], ['C++']]
```

The expected output is:

    |    |   ('C++',) |   ('Java',) |   ('Python',) |
    |---:|-----------:|------------:|--------------:|
    |  0 |          0 |           0 |             1 |
    |  1 |          0 |           1 |             0 |
    |  2 |          0 |           0 |             0 |
    |  3 |          1 |           0 |             0 |

- [Resource 1](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

In [19]:
X_test = [['Python'], ['Java'], ['C'], ['C++']]
df = pd.DataFrame(enc.transform(X_test).toarray().astype(np.int8), columns=enc.categories_)
df.head().to_markdown()

ImportError: `Import tabulate` failed.  Use pip or conda to install the tabulate package.