In [8]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

The goal of this exercise is to learn how to use an `Imputer` to fill missing values on a basic example.

```python
train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]
```

In [9]:
train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]

1. Fit the `SimpleImputer` on the data. Print the `statistics_`. Check that the statistics match `np.nanmean(train_data, axis=0)`.

In [15]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(train_data)
print(imp_mean.statistics_)
print(np.nanmean(train_data, axis=0))

[ 4. 13.  6.]
[ 4. 13.  6.]


2. Fill the missing values in `train_data` using the fitted `imputer` and `transform`.

In [17]:
imp_mean.transform(train_data)

array([[ 7.,  6.,  5.],
       [ 4., 13.,  5.],
       [ 1., 20.,  8.]])

3. Fill the missing values in `test_data` using the fitted `imputer` and `transform`.

```python
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]
```

In [11]:
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]

